### ISSUE TITLE
track artists don't get added from VA album

### ISSUE THREAD

**Issue by xeroxcat** [snejus/beets-bandcamp#13]
Hi, noticed when importing a VA album the individual track artists weren't getting imported. Idk if this is a persistent issue but would make sense that it was from looking at the track JSONDicts. Made a quick fix on a fork https://github.com/xeroxcat/beets-bandcamp/commit/78716b2994c852ae42309e01cec7cd16e462b86c that works for my circumstance. Would have made a PR but its a tiny fix and I could imagine you'd wanna implement it a bit more cleanly or run more comprehensive tests - I just made sure it worked for this album:
https://alienheartrecordz.bandcamp.com/album/songs-for-the-interstellar-heart-vol-1
thanks for the plugin

**Comment by snejus** [comment]
Hey, happy that works for you! Just had a look at the html/json of your URL and it seems like bandcamp have updated their html! Previously a track was just a track name without any pointers about who's the artist (that's why that absolutely unreadable piece of parser code exists). Though it seems like it may now potentially get thrown out :) I'll cycle through a couple of more VA albums to check whether they contain the updates and will implement it.

Sick album by the way!

**Comment by snejus** [comment]
closed due to lack of reply

**Comment by snejus** [comment]
Accidentally closed it previously, thinking it was another issue! 

It should now be handled in 0.9.0 :)

**Comment by xeroxcat** [comment]
Hey thanks for the quick response, I've had my head in other issues but thanks for maintaining this project! I'll update next time i'm importing and check it out!
