### ISSUE TITLE
Unexpected html while scraping album 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by knowhy** [snejus/beets-bandcamp#8]
I'm getting `'NoneType' object has no attribute 'text'` error when trying to import using the plugin. I have tested with the latest state of master and dev branch (same result).

```
[me@laptop VA THE PUJA RITUAL compiled by Gandharva Project (Free Download)]$ beet -v import -S https://sacredsoundrecs.bandcamp.com/album/va-the-puja-ritual-compiled-by-gandharva-project-free-download .
user configuration: /home/me/.config/beets/config.yaml
data directory: /home/me/.config/beets
plugin paths: 
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
lastgenre: Loading canonicalization tree /usr/lib/python3.9/site-packages/beetsplug/lastgenre/genres-tree.yaml
library database: /home/me/.config/beets/library.db
library directory: /home/me/music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Looking up: /home/me/import/Gandharva Project/VA THE PUJA RITUAL compiled by Gandharva Project (Free Download)
Tagging Gandharva Project - VA THE PUJA RITUAL compiled by Gandharva Project (Free Download)
Searching for album ID: https://sacredsoundrecs.bandcamp.com/album/va-the-puja-ritual-compiled-by-gandharva-project-free-download
Requesting MusicBrainz release https://sacredsoundrecs.bandcamp.com/album/va-the-puja-ritual-compiled-by-gandharva-project-free-download
Invalid MBID (https://sacredsoundrecs.bandcamp.com/album/va-the-puja-ritual-compiled-by-gandharva-project-free-download).
discogs: Searching for release https://sacredsoundrecs.bandcamp.com/album/va-the-puja-ritual-compiled-by-gandharva-project-free-download
bandcamp: Unexpected html while scraping album 'https://sacredsoundrecs.bandcamp.com/album/va-the-puja-ritual-compiled-by-gandharva-project-free-download': 'NoneType' object has no attribute 'text'
Evaluating 0 candidates.
```

**Comment by knowhy** [comment]
I installed using `sudo poetry build && sudo poetry install`. I'm not familiar with the tooling, maybe I did something wrong there? Can you add instructions to the README?

**Comment by snejus** [comment]
hey @knowhy, in terms of installation you should just run `pip install beetcamp` (note the namechange) as [the readme outlines](https://github.com/snejus/beets-bandcamp#installation) - easy as that. 

In terms of using poetry, these are correct commands - except for the `sudo`. Just fyi, if you have it installed at the system level, try cleaning it and install it for your user (their documentation have guidelines on this) - you'll avoid a good deal of issues that would come up otherwise.

I can see that your beets are still using the old `beets-beetcamp` version which is broken. Just try installing this with `pip` and you should be fine. 

Absolutely sick sound by the way, got a copy myself:
![image](https://user-images.githubusercontent.com/16212750/106348100-8eda2700-62bb-11eb-9864-0e4a6937e513.png)

Also - it's enough to provide the path to the album - plugin will find it on bandcamp.

**Comment by snejus** [comment]
Closing this since that isn't something that needs to be solved by the library.
